### ISSUE TITLE
Please consider node-red-contrib- naming guidelines

### ISSUE THREAD

**Issue by knolleary** [Cloudino/Cloudino-Node-RED#1]
Hi,

thanks for sharing your node with the community. One small request - we do ask for nodes that aren't maintained by the main node-red project to use `node-red-contrib-` prefix to their npm package name. We want to keep it clear to the community which nodes are maintained by us and which are from the community.

http://nodered.org/docs/creating-nodes/packaging#naming

You're free to use the name you want, but it would be nice if you'd consider this request.

Thanks! Nick

**Comment by softjei** [comment]
OK, I will change the name...

Best regards,

Javier Solís

2016-03-24 10:33 GMT-06:00 knolleary notifications@github.com:

**Comment by softjei** [comment]
Done
